### ISSUE TITLE
Capacitor Banks Can Cause Integer Overflow

### ISSUE THREAD

**Issue by Internal-Exception** [OpenMods/OpenPeripheral#191]
If a capacitor bank is larger than 2^31, being represented by a 32 bit integer, it overflows. Realizing this is impossible to fix outright with ComputerCraft's 32-bit system, here are my suggestions.

capacitor.getEnergyStoredMRF
This would allow for exactly 1 million times more capacitors, and would be substantial for computing percentages and giving estimates of the energy stored.

capacitor.getCapacitorCount
capacitor.getEnergyStoredPercentage
This would completely fix the problem, but not allow for quite as much precision. With this method we could evaluate 2^31 capacitors, but only to so many decimal places because of the percentage approach.

**Comment by AngellusMortis** [comment]
@boq is right, this is not an issue with OpenPeripherals, it is a limitation of the RF-API. It caps out at `INT_MAX` so that prevents `getEnergyStored` and `getMaxEnergyStored` from getting the proper value inside of storage blocks that hold over that amount.

**Comment by Vexatos** [comment]
The official ComputerCraft/OpenComputers integration for EnderIO is in a mod called [Computronics](http://wiki.vex.tty.sh/wiki:computronics). So you shouldn't even get values this large without Computronics being installed.

**Comment by boq** [comment]
@Vexatos I'm sorry, but "official"? Do you have guarantee that non-API parts used by Computronics  are not suddenly going to change?

**Comment by Vexatos** [comment]
@boq "official" as in as soon as something changes, I will update Computronics accordingly.

**Comment by Vexatos** [comment]
... Any news on this? I tested a little and so far I've not been able to reproduce any issue like the one described here. I tested with large Capacitor Bank multiblocks and so far always got the correct values.
