### ISSUE TITLE
Furnace doesn't work as peripheral after smelting

### ISSUE THREAD

**Issue by ParapetCloud** [OpenMods/OpenPeripheral#198]
in the lua interpreter I wrote
furnace = peripheral.wrap("top")
furnace.getAllStacks()
and it gave me all the info. 
I then smelted something and tried furnace.getAllStacks() again and it returned nil. 
I tried re-wrapping and it still returned nil. 
I tried furnace.getInventoryName() and it returned nil.
I tried furnace.isBurning() and it returned nil
OpenPeripheralCore Version 0.41
OpenPeripheralAddons Version 0.1.5

**Comment by nevercast** [comment]
Just so there is a "Fix" for anyone searching issues.
Use a modem, for some reason the logic for a modem on a furnace is different to a direct connection in ComputerCraft.
