### ISSUE TITLE
sensor.getPlayerNames() gives attempt to call nil

### ISSUE THREAD

**Issue by DarthRevanBAS** [OpenMods/OpenPeripheral#220]
I was trying to do a tracker prog, and this just happened with every entity i tried whether its players, mo s, inventories etc

**Comment by Vexatos** [comment]
Did you wrap the peripheral first?

**Comment by boq** [comment]
It was replaced with method returning player profile (name + uuid), due to vanilla changes.

Please use `.listMethods()` and/or documentation program before reporting issues like this.
