### ISSUE TITLE
Applied Energistics 2

### ISSUE THREAD

**Issue by jilleJr** [OpenMods/OpenPeripheral#222]
I wan't to be able to request items from an AE system but I can not find how to do so...

I have found lots of others requesting but I think that is for the old AE not AE2...

I'm trying to hook up my computer to the AE controller, a cable, a ME interface, ME terminal, but no luck. The only methods I have available is to check the targets power consumption ;(

![methods for the ME controller](http://i.imgur.com/HVwaZng.png?2)

For some reason there's `pushItem` and similar inventory methods but I can't do anything with them; for example `getAllStacks` gives an empty table (and my AE system is not empty).

**Comment by boq** [comment]
AE integration was removed due to deprecation, AE2 is not implemented. What you see are generic inventory method. It's up to mod author do decide what they do - so they might be just stubs without any functionality.

**Comment by jilleJr** [comment]
Whaaaaaaaaaaaaaaaat that stinks! Is it gone forever or is there a way to re-implement the integration?

**Comment by boq** [comment]
Well, we got tons of complaints about lack of NBT data support in previous implementation, so it's on hold until we figure that out. Or maybe someone else does. It's open source project, after all.
