### ISSUE TITLE
pullItemIntoSlot returns nil value

### ISSUE THREAD

**Issue by Unknownk** [OpenMods/OpenPeripheral#224]
hi,

i have an issue with the function "pullItemIntoSlot()".

I have the following program:

p = peripheral.wrap("west")
p.pullItemIntoSlot("up",1,1,1)

If i run this programm i get the error "2: attempt to index ? (a nil value)".

This runs on an advanced computer.

Versions: (direwolf 1.7 pack v1.0.1)
CC: 1.65
OpenModsLib 0.6
OpenPeripheralAddons 0.2.0
OpenPeripheralCore 0.5.0

Hopefully someone can help me. Thank you in advance!

**Comment by boq** [comment]
> Direwolf 1.7 pack v1.0.1

There's your problem. Update to 1.0.3
