### ISSUE TITLE
No longer works serverside only?

### ISSUE THREAD

**Issue by menglish59** [OpenMods/OpenPeripheral#225]
Found on our server that where the Core used to run serverside only it now no longer does.  After abit of googling i came accros this.
https://mineyourmind.net/forum/threads/tdt-openperipheral-core.4822/
Is it itentional then that serverside only is no longer a thing?  Or was it simply overlooked?

**Comment by boq** [comment]
Oversight. Majority of users probably just installs that on client (since it's needed in singleplayer).
