### ISSUE TITLE
Something is missing from the build instructions, or build is broken?

### ISSUE THREAD

**Issue by prozacgod** [OpenMods/OpenPeripheral#226]
http://pastebin.com/6D8V3LGw

```
:OpenModsLib:javadoc
/home/prozacgod/Workspace/mc/OpenPeripheral/OpenModsLib/src/main/java/openmods/integration/modules/BuildCraftPipes.java:11: error: package buildcraft.api.transport does not exist
import buildcraft.api.transport.IPipeTile;
                               ^
/home/prozacgod/Workspace/mc/OpenPeripheral/OpenModsLib/src/main/java/openmods/inventory/legacy/ItemDistribution.java:137: error: @param name not found
	 * @param target
	          ^
/home/prozacgod/Workspace/mc/OpenPeripheral/OpenModsLib/src/main/java/openmods/inventory/legacy/ItemDistribution.java:146: warning: no description for @param
	 * @param doMove
	   ^
```

Starts there, bunch of things mentioned in that build log.

My environment my also be naive, I'm very new to Java - (developer in a multitude of other languages.)

**Comment by boq** [comment]
Something in your environment decided to fail on Javadoc error. This problem didn't occur on our build server or in local dev.

I'm not sure if setting explicitly this flag with this commit will work, but I can always try.

**Comment by boq** [comment]
Ok, so it was Java 8 problem (javadoc is suddenly much more restrictive). Should work now.
