### ISSUE TITLE
A trapped chest next to a normal chest is treated as a doublechest

### ISSUE THREAD

**Issue by DelusionalLogic** [OpenMods/OpenPeripheral#228]
If you place a trapped chest next to a normal chest and wrap the trapped chest as a peripheral you can interact with items in the normal chest as if they were a double-chest.

If the normal chest is a double chest next to a trapped chest you can interact with half of the double-chest (the one that controls the half of the chest that the trapped chest is touching)

I'm almost certain it's a bug due to you not discriminating between trapped and normal chests, and therefore just seeing two chests next to each other and assuming they must be a single double-chest.

**Comment by boq** [comment]
Good report, bad repo (inventory methods are in OpenPeripheral-Integration, actual bug in OpenModsLib). Anyway, fixed.
