### ISSUE TITLE
Terminal Glasses not recognizing users or syncing

### ISSUE THREAD

**Issue by soupmeister** [OpenMods/OpenPeripheral#229]
I am able to wrap the bridge and call its methods just fine.  I've also noticed that getUsers() returns a blank table, and chat commands don't work, so I know it's not a graphical glitch of being unable to render the overlay. I've double checked my glasses match the GUID of the bridge, and syncing does not help.  Here's an example of the simple code I'm using:

t = peripheral.wrap("left")
t.addBox(1,1,10,10,0xFFFFFF,0.2)
t.sync()
t.getUsers()

I have created a new bridge, new glasses, and tried rebooting while wearing the glasses, along with destroying all involved blocks and starting from scratch.  Thanks.

Running OpenPeripheralsCore 0.6.0, OpenPeripheralIntegration 0.1.0, and OpenPeripheralAddons 0.2.0 on a FluxGalaxy v0.7.16 server.

**Comment by soupmeister** [comment]
Running OpenPeripheralsCore 0.6.0, OpenPeripheralIntegration 0.1.0, and OpenPeripheralAddons 0.2.0 on a FluxGalaxy v0.7.16 server.

**Comment by nevercast** [comment]
Issue locked, discussion to follow here: https://github.com/OpenMods/OpenPeripheral-Addons/issues/51

Will close at the conclusion of the issue on OpenPeripheral-Addons.
