### ISSUE TITLE
need update with last ComputerCraft 1.7

### ISSUE THREAD

**Issue by smenes** [OpenMods/OpenPeripheral#230]
[Client thread/ERROR] [FML/]: The mod OpenPeripheral (OpenPeripheralAddons) requires mod versions [ComputerCraft@[1.64,]] to be available

**Comment by Vexatos** [comment]
Just wait for
a) ComputerCraft 1.7.1
b) dan200 fixes his broken versioning system.

**Comment by boq** [comment]
Explanation: 1.7 < 1.64 < 1.71. Yup, #BlameDan

**Comment by Morketh** [comment]
there was an update to CC 1.71 check and see if it was fixed if so please close the issue

**Comment by excelcrafter** [comment]
cc 1.72

**Comment by boq** [comment]
We never needed update. Released version works with CC 1.73.

**Comment by smenes** [comment]
thanks

**Comment by boq** [comment]
I never did anything. Just waited... :P

**Comment by excelcrafter** [comment]
I was waiting too, didnt expect newer version of cc so fast :-D
