### ISSUE TITLE
possible Crash/Error/bug with OpenComputers

### ISSUE THREAD

**Issue by lasnom** [OpenMods/OpenPeripheral#239]
I run into an exception with OpenComputers and OpenPeripheral. 
If an interfacable block (something like an Chest, ME-Interface, OpenPeripherals Sensor)  gets placed next to an OpenComputers Adapter (which is connected to an computer..) the player gets kicked from the server. After relogging the block is placed and still in the inventory. Braking the block leads to another kick and an dupe of the item.
Reproducing the same situation in single player results in an crash of the game. 
Removing OpenPeripheralCore/Addons/Integration resolves this issue. 
Using the latest OpenComputers version leads to the same bahviour.
I'm not sure, if OpenPeripheral or OC (or something else..) causes this behaviour, but after looking at the logs, it seems like openmods is at least heavily involved. 

Server output snippets and singleplayer crashlog:
https://www.dropbox.com/s/fsjygz4gw79gti8/openerr.txt?dl=0

Mod/Forge Versions:
```
Forge:   1.7.10-Forge10.13.2.1351-1.7.10

OpenBlocks-1.7.10-1.4.2-snapshot-611.jar
OpenComputers-MC1.7.10-1.5.8.17-universal.jar
OpenModsLib-1.7.10-0.7.2-snapshot-349.jar
OpenPeripheralAddons-1.7.10-0.3.1-snapshot-196.jar
OpenPeripheralCore-1.7.10-1.1.1-snapshot-222.jar
OpenPeripheralIntegration-1.7.10-0.2.2-snapshot-64.jar
```

**Comment by Selim042** [comment]
Sounds like a problem with OpenPeripheral Intergration.
https://github.com/OpenMods/OpenPeripheral-Integration

**Comment by boq** [comment]
Please add following VM args:
```
-Dlegacy.debugClassLoading=true -Dlegacy.debugClassLoadingFiner=true
```
It will generate lots of logs. If you have problem with posting whole file, then just copy lines that contain `Exception encountered attempting classloading of`  + (let's say) 128 before and after - just to get actual stacktraces.

**Comment by lasnom** [comment]
Lots of logs...thats true -> 1.1 GB. I uploaded the complete startup log as compressed archive. 

https://www.dropbox.com/s/0k5o2phw0nzlryt/fml-client-latest.zip?dl=0

**Comment by boq** [comment]
Whoah...

Anyway, looks like it's caused by file LambdaLib-1.0beta3.jar. It's open source ([here](https://github.com/LambdaInnovation)) and issue seems to be fixed, at least in code. OpenEye has already noticed something that looks like new version: lambdalib-1.0beta3pr2.jar.

**Comment by lasnom** [comment]
Kk, tried it without LambdaLib and everything works file. 
Tanks for looking into this :)

**Comment by boq** [comment]
I will probably implement some kind of fallback, because this kind of issue may be not that uncommon in other coremods.

**Comment by lasnom** [comment]
Not the worst idea. Maybe with an big warning in case something like this happens... at least for easier error reporting. I've been searching for errors at the completely wrong end~~

**Comment by boq** [comment]
Well, it was good angle, because OpenPeripheral does something unusual, and it may be broken by badly written coremod. 99% of mods already do it right way, but making that bug doesn't immediately crash, so few may slip.

**Comment by lasnom** [comment]
It's always hard to tell, which part of code influences another... (or in case of minecraft..which mod breakes something of another mod..). Nasty little side effects. But you have been fast in finding the sollution... thx again :)
