### ISSUE TITLE
sensor return list of methods instead of mobData

### ISSUE THREAD

**Issue by Terpo** [OpenMods/OpenPeripheral#240]
OpenMods:
OpenBlocks-1.7.10-1.4.1-snapshot-607.jar
OpenModsLib-1.7.10-0.7.1-snapshot-345.jar
OpenPeripheralAddons-1.7.10-0.3.1-snapshot-195.jar
OpenPeripheralCore-1.7.10-1.1-snapshot-220.jar
OpenPeripheralIntegration-1.7.10-0.2.1-snapshot-63.jar

Modlist:
http://blog.terpo.org/upload/mc/modlist.txt

My wither spawning is using a sensor to detect mobs like the wither. Normally there is only one mob, or no mob in range. 

The program in short form:

s = peripheral.wrap("left") -> sensor
mobs = s.getMobIds()  -> mob ids  -> is detecting the wither (example: 7419601)
for k, v in pairs( s.getMobData(7419601) ) do
	print(k)
	print(v)
end

Now, instead of printing the data of the mob, I am getting the list of methods for the sensor:
listSources 
function: xxxxxxxx
getAdvancedMethodsData
function: xxxxxxxx
... and so on

In this version the sensor worked fine with the same code:
OpenBlocks-1.7.10-1.3-snapshot-569.jar
OpenModsLib-1.7.10-0.6-snapshot-321.jar
OpenPeripheralAddons-1.7.10-0.2.0-snapshot-178.jar
OpenPeripheralCore-1.7.10-0.6.0-snapshot-208.jar
OpenPeripheralIntegration-1.7.10-0.1.0-snapshot-49.jar

**Comment by boq** [comment]
Expected behaviour. Try to play with those methods or just check our [FAQ](http://openmods.info/faq.html) (last question).
