### ISSUE TITLE
[Suggestion] Return localized peripheral name

### ISSUE THREAD

**Issue by thatcraniumguy** [OpenMods/OpenPeripheral#242]
Being able to wrap peripherals allows us to get a peripheral type using peripheral.getType(), however many mods only return a very user-unfriendly name. Case in point, Thermal Expansion. Most of the types returned start with tile_thermalexpansion_etc_more_crap_like_this, which makes it very annoying to read on things that you want to display the proper peripheral type. I suggest a new function to be added that would allow the user to display a much easier to read name.

**Comment by boq** [comment]
Peripheral types cannot be changed in runtime.

But here's alternative:
- OpenPeripheral creates file `peripheral_names.txt` in config folder. It contains (tile entity class, peripheral type) pairs
- every time new peripheral class is added, entry is added to this file
- any change in that file will be visible after restart
- initial predefined values are defined [here](https://github.com/OpenMods/OpenPeripheral/blob/master/src/main/resources/default_names.txt) - this will be expanded in future (you can try to PR your customized file)
