### ISSUE TITLE
Sensor getPlayerByName() 

### ISSUE THREAD

**Issue by Michal330** [OpenMods/OpenPeripheral#245]
Method getPlayerByName always returns an empty table.

I use this versions
OpenPeripheralCore-1.1.1
OpenPeripheralAddons-0.3.1
OpenPeripheralIntegration-0.2.2

**Comment by boq** [comment]
Ah, yes, let me just call my friends at NSA and ask them to extract versions of OpenPeripheralCore, OpenPeripheralIntegration and OpenPeripheralAddons you are using. And what exactly were you doing. Also, what exactly happened. And possibly your logs.

**Comment by Michal330** [comment]
I use this versions
OpenPeripheralCore-1.1.1
OpenPeripheralAddons-0.3.1
OpenPeripheralIntegration-0.2.2

sensor.getPlayerByName()
This method always returns an empty table.

**Comment by boq** [comment]
Please run following commands in interpreter and post result (may be screenshot):
```lua
p = <peripheral>
u = <username>

print(p.getPlayerByName(u))
t = p.getPlayerByName(u)
print(type(t))
print(type(t.all))
```

**Comment by Michal330** [comment]
result
![image](https://cloud.githubusercontent.com/assets/12269903/7798229/8c661d3c-02f7-11e5-941f-3fa0fb9f65d2.png)

**Comment by boq** [comment]
Ah, it's what I expected. This table is far from being empty. See last question in our [FAQ](http://openmods.info/faq.html).

**Comment by Michal330** [comment]
Thank you.
I'm sory . I did not know.

**Comment by popcorn9499** [comment]
can anyone explain what im doing wrong i didnt understand the FAQ
thanks
