### ISSUE TITLE
ComputerCraft 1.7 not found when launching Minecraft

### ISSUE THREAD

**Issue by Noorquacker** [OpenMods/OpenPeripheral#246]
I just installed the most recent OpenModsLib, OpenPeripheral, and ComputerCraft but only version 1.70 and OpenPeripheral is not finding ComputerCraft. When I launch Minecraft, it says this exactly as I see it:

Forge Mod Loader has found a problem with your minecraft installation
The mods and versions listed below could not be found

ComputerCraft : [1.70,]

The file 'ForgeModLoader-client-0.log' contains more information

So I checked and saw CC 1.7 in my mods folder. Then, disabling OpenPeripheral I looked through mods loaded and ComputerCraft was there with its logo and its pack.info contents there. I can't find the log file because it's my own unlisted FTB modpack(now I forgot my password for it, great) which is stored differently than normal FTB modpacks.

**Comment by boq** [comment]
It's not ComputerCraft 1.70, it's 1.7. And 1.6 < 1.7 < 1.64 < 1.71. OP is deliberately requiring non-existing version 1.70 to make sure we aren't loading with 1.6X.
