### ISSUE TITLE
Server Crash with PeripheralProxy

### ISSUE THREAD

**Issue by Xiaminou** [OpenMods/OpenPeripheral#248]
![2015-06-13_15 33 07](https://cloud.githubusercontent.com/assets/8670392/8144492/c2852d56-11e1-11e5-8b15-803266f97ed6.png)
![2015-06-13_15 36 18](https://cloud.githubusercontent.com/assets/8670392/8144494/f726521a-11e1-11e5-8168-ef96f5868e25.png)

I have been using a basic CC Touchscreen mystcraft portal program for days now on my server without any problem, today when I booted the server all my computers were down. When I tried to reboot them I got nothing so I destroyed one and tried  to replace it, still nothing. I then tried to replace the modems and when I tried right clicked the new modem that's on the Peripheral Proxy I got this crash:
http://pastebin.com/h63kE2W6.

It's a big problem for me because my whole base is seperated in many parts accross different ages and I rely entirely on this to travel between the different locations. That and the fact that it completly crash my server and client.

EDIT: I somehow managed to fix one of the computers and run the portal program however I have no idea how I did it because I can't reproduce it on any other computers.
EDIT2: Another crash from trying to reboot my Direwolf20's Turbine program computer: http://pastebin.com/fNBtWz0V

**Comment by boq** [comment]
Oh my, I haven's seen that one in a while...

Duplicate: OpenMods/OpenPeripheral#206, OpenMods/OpenPeripheral#207, OpenMods/OpenPeripheral#217, OpenMods/OpenPeripheral#221, OpenMods/OpenPeripheral-Integration#1, OpenMods/OpenPeripheral-Addons#40, OpenMods/OpenPeripheral-Addons#42 OpenMods/OpenPeripheral-Addons#45.

This time it's not ProjectRed, so just run `/om_source_c class dan200.computercraft.api.peripheral.IComputerAccess` and blame all mods that show up.

**Comment by Xiaminou** [comment]
I have no idea where to run that or what to do with what's going to come out of it.
