### ISSUE TITLE
Terminal Glasses not working AIO-4

### ISSUE THREAD

**Issue by tethlah** [OpenMods/OpenPeripheral#250]
For some reason, no matter what I do, I can't get terminal glasses to work,  even a simple hello world, or even using this tutorial:  http://ftbwiki.org/Terminal_Glasses

I'm using the version with the .sync()

However, still nothing.

**Comment by tethlah** [comment]
Here is the exact code:  http://pastebin.com/mH79RXbQ

**Comment by tethlah** [comment]
BTW, I've also tried using OpenPeripheralCore 1.1.1, Addons 0.3.1, and Integration 0.2.2 instead of AIO-4

**Comment by boq** [comment]
Just a simple sanity check: you are calling 'start()' anywhere?

**Comment by tethlah** [comment]
Welp, that was stupid, lol

Ok, it's working.  Now I just gotta figure out where to add the sync() in this monster http://pastebin.com/kXLnc4xf

**Comment by boq** [comment]
After you are done with all updates and before you start sleeping or waiting for user input.

Also, this particular approach where you `.clear()` stuff every tick isn't very effective (at least in that version). But it still works.

**Comment by tethlah** [comment]
Gotcha, yeah that program was a control program I've been using off a forum.
