### ISSUE TITLE
scala.actors.threadpool.Arrays in release.

### ISSUE THREAD

**Issue by SquidDev** [OpenMods/OpenPeripheral#252]
[EnumeratedRange](https://github.com/OpenMods/OpenPeripheral/blob/b7dbb141cc2a810626ec8bd8d829a54c486b921f/src/main/java/openperipheral/adapter/types/EnumeratedRange.java#L7) (and [StructTest](https://github.com/OpenMods/OpenPeripheral/blob/3d533606f4ea9b7f2609dbee6638c5c01f4c05fd/src/test/java/openperipheral/tests/StructTest.java)) include references to `scala.actors.threadpool.Arrays.asList` instead of `java.util.Arrays.asList`. This class is not available during runtime and so results in NoClassDefFoundError.

[Example log](http://puu.sh/j3H6t/0340fb6426.log)

**Comment by boq** [comment]
*snapshot, not release. Anyway, thanks for reporting. I really hate that class...
