### ISSUE TITLE
Crash when calling getStackInSlot on chest with weird bee in it

### ISSUE THREAD

**Issue by Wyvern67** [OpenMods/OpenPeripheral#254]
VERSION:
Minecraft 1.7.10
Infinity 1.9.0
ComputerCraft 1.74
OpenBlocks-1.7.10-1.4.3
OpenModsLib-1.7.10-0.7.3
OpenPeripheralAddons-1.7.10-0.3.1b
OpenPeripheralCore-1.7.10-1.1.1
OpenPeripheralIntergration-1.7.10-0.2.2

EXPECTED RESULT:
I'd expect it not to error out on any item

REPRODUCTION STEPS:
1. Place a drone such as this one in the first slot of a chest
http://i.imgur.com/UPxOawi.png?1

2. Execute this code

c = peripheral.find("ender_chest")
c.getStackInSlot(1)

ERROR:
lua:1:  forestry.api.apiculture.IBee.isIrregularMating()Z
http://i.imgur.com/RF5YhSJ.png?1

**Comment by boq** [comment]
#253, OpenMods/OpenPeripheral-Integration#16 duplicate
