### ISSUE TITLE
Terminal Glasses add component missing function

### ISSUE THREAD

**Issue by alandoyle95** [OpenMods/OpenPeripheral#255]
I feel like this function should be added.. its a simple one, but i feel its needed.. unless i am wrong.

after you add a component (addBox, addText, addIcon, etc.) it returns an OBJECT of functions related to that component it generates an ID and it is never the same (as far as i can tell after you restart the computer it gets a different one) so i feel like there should be a getID function included in the returned object.

i feel like its a simple function that should have been added in from the start, but im sure that there are reasons it is not in there, but i have not found anyone else that has thought about this or has came up with a way of doing this.. only reason i found it was because im trying to make a stupidly complex terminal glasses program.

**Comment by Sabbath93** [comment]
Have you tried turning it off and on again?

**Comment by nevercast** [comment]
Just to clarify, what would the purpose of having the ID be?
Since after a computer/server restart the UI will need to be rebuilt, the ID doesn't provide any persistence.

**Comment by nevercast** [comment]
Also, an aside, the correct place to report this issue is https://github.com/OpenMods/OpenPeripheral-Addons/.

Don't worry about moving the issue, I can cross reference it from the other project. But just for future. Cheers.

**Comment by alandoyle95** [comment]
sorry about that... and the ID would be used to detect clicking events for an object so that you can just make buttons and not have to use the X and the Y to determine it. it does not even have to be a function per-say, just being able to get the ID when the component is created would be enough. i just this it would add more possibility to terminal glasses programs, and also be able to simplify some code.

my example of the use would basically be scroll bar buttons. to scroll though a list of items on the screen. and the code would be super simple if you could get the component ID, since it gives you what component you clicked on from the event pulled.

**Comment by nevercast** [comment]
Okay, it's been 2 years since I've touched OPA, can you tell me what values are given to you in a pullEvent?

**Comment by alandoyle95** [comment]
https://gist.github.com/boq/9a098b89ee102cbf1b2b

there is a list :)

**Comment by nevercast** [comment]
Thanks, it looks like the Drawable object already exposes a getId() function, right next to the delete() function.

Have you tried this?

**Comment by alandoyle95** [comment]
hmm.. its not in the list of objects returned.. i'll try that now and edit this post with the results..

**Comment by nevercast** [comment]
It's not a property, it's a ScriptCallable function, it might not be visible in the metadata of the object. Please check it and let me know.

**Comment by alandoyle95** [comment]
ok, im semi smart when it comes to computercraft.. but i still have no idea what you just said. or how i would go about testing that.

**Comment by nevercast** [comment]
Just call getId() on the object returned by addBox (:

**Comment by alandoyle95** [comment]
ok haha thats what i thought and it returns nil :(

**Comment by nevercast** [comment]
You can call delete on the object?

**Comment by alandoyle95** [comment]
nope

**Comment by alandoyle95** [comment]
i should note that im on version 0.3.1 more than likely not the most updated one.

**Comment by nevercast** [comment]
It was foolish of me not to ask for version information first. One moment I'll verify it works at my end.

**Comment by alandoyle95** [comment]
yea its also my bad that i didnt check to see what the latest version was, i cant seem to find a change log on it either...

**Comment by nevercast** [comment]
Do you have a date? Because it needs to be newer than Feb 5th this year
https://github.com/OpenMods/OpenPeripheral-Addons/commit/6c54fe360ff8e71bc684fcc2a2f7304e5c5030e2

**Comment by nevercast** [comment]
Build 162 or newer

**Comment by alandoyle95** [comment]
sadly i dont have a build number (using a pre made pack) but seems as though it all got added :D so thank you for your help, i'll just update the mods and then mess around with the new version!

**Comment by nevercast** [comment]
Let me know if updating does not work for you, between now and such time I should be able to actually test OPA. I only started developing again yesterday so no test environment for OP(A/I) yet.

**Comment by alandoyle95** [comment]
will do!

**Comment by alandoyle95** [comment]
Yep methods are all there and work :D AWESOME thanks for the help, here is the updated list of methods from addBox if anyone wants it...

http://pastebin.com/gFRGUvNr
