### ISSUE TITLE
[1.7]Program breaks when reading Forestry Bee nbt

### ISSUE THREAD

**Issue by Lyl4c** [OpenMods/OpenPeripheral#257]
Minecraft 1.7.10
ComputerCraft v1.74
Open Peripheral Addons 0.3.1b
Open Peripheral Core 1.1.1
Open Peripheral Integration 0.2.2
Forestry 3.6.2.19

forestry.api.apiculture.IBee.isIrregularMating()Z

This is the error I get when | getStackInSlot(i) | is used to retrieve information inside a chest. Specifically if a forestry bee is placed any where inside said chest.

This Program
http://pastebin.com/dgqB4kef

can be used to recreate the error. Place a turtle on top of a chest and place a forestry bee in the chest and run the program.

I expected the program to continue to run smoothly and to return true upon reaching the slot the bee is in.

**Comment by boq** [comment]
#253, #254, OpenMods/OpenPeripheral-Integration#16 duplicate
