### ISSUE TITLE
pushItem and pullItem are both returning Other inventory not found

### ISSUE THREAD

**Issue by 111poiss111** [OpenMods/OpenPeripheral#260]
Using latest FTB Infinity modpack(2.1.2) I have not successfully managed to move items from one inventory to another. Functions always returns "Other inventory not found".
OpenPeripheral 1.2
![2015-11-16_00 20 34](https://cloud.githubusercontent.com/assets/5306169/11171423/df4a24c8-8bf8-11e5-905f-fc10ba5a82df.png)

**Comment by boq** [comment]
Command is executed on peripheral (chest) and not on computer, therefore other inventory must be adjacent to peripheral.

If it was connected by modem, would you also expect it to push items into chest placed by computer?

**Comment by 111poiss111** [comment]
For some reason it never occured to me. Now that you say that, it makes sense. Sorry.
