### ISSUE TITLE
Computercraft Error. message after trying to call mekanism peripherals.

### ISSUE THREAD

**Issue by Feelthethunder** [OpenMods/OpenPeripheral#261]
As the title says computercraft doesn't like to use the peripherals from mekanism. Specifically the energy cubes. I have tried everything and have all the latest versions of computercraft, mekanism, and openperipherals. After trying an advanced program, I boiled it down to a very very basic one and it still didn't work.
Code:

local cube = peripheral.wrap("left")
local energy = cube.getStored()
print(energy)

The output of the program was Error.
Without the () at the end of getStored I get a function: 38f62f8f error
Yet when I use the lua script and use the command:

peripheral.getMethods("left")

I get all of the methods:
getStored
getOutput
getMaxEnergy
getEnergyNeeded

all of these peripherals come up with the same Error. message when I try to call them.
If anyone can help and save me some more hair tearing out that would be appreciated. Thanks.

**Comment by boq** [comment]
This peripheral is not provided by OpenPeripheral - notice missing 'listMethods' and 'getAdvancedMethodsData'.

It looks like peripheral code provided by Mekanism itself is broken. I'm... not really sure what happened there, but it does not look like it was generated by sane compiler...

**Comment by boq** [comment]
It looks like it was already fixed in Mekanism. And yes, it was generated by compiler, just by very broken code...

**Comment by Feelthethunder** [comment]
Could you please explain what I must do to fix this then? I am still lost.

**Comment by boq** [comment]
"looks like it was already fixed in Mekanism."

So just wait for next release, where this fix aidancbrady/Mekanism#3014 is included.

**Comment by Feelthethunder** [comment]
Alright thanks for the help. Let the waiting game begin.
