### ISSUE TITLE
Railcraft Boiler Temperature

### ISSUE THREAD

**Issue by Invalidnull** [OpenMods/OpenPeripheral#264]
In reference to issue #121, I cannot seem to find the method to read the temperature from a Railcraft boiler. It does not appear in the method list nor does it run when I call it.

Any insight would be greatly appreciated, thank you for the fantastic mod.

FTB Infinity Evolved version 2.2.2
Minecraft 1.7.10
OpenPeripheralCore version 1.2
OpenPeripheralAddons version 0.4
OpenPeripheralIntegration version 0.3
OpenModsLib version 0.8

**Comment by boq** [comment]
It is still in there.

Please note that it will only show when you attach computer to firebox.

**Comment by Invalidnull** [comment]
Thank you for the quick response and forgive my ignorance. That make a lot of sense.
