### ISSUE TITLE
incorrect version info maybe?

### ISSUE THREAD

**Issue by stoops420** [OpenMods/OpenPeripheral#265]
I just updated my custom pack inspired by infinity evolved to the latest versions of the openmods pack and OPeripheralCore wont start because its looking for "OpenMods@ (0.8,0.9)".

I know I have the correct mods and versions loaded. Any Suggestions?

**Comment by boq** [comment]
It's actually `OpenMods@[0.8,0.9)` and it means any (and only) 0.8 version. You haven't updated everything.
