### ISSUE TITLE
Domain registration expired

### ISSUE THREAD

**Issue by AnrDaemon** [OpenMods/OpenPeripheral#269]
http://openperipheral.info/ points to a stub page with
```
NOTICE: This domain name expired on 6/23/2016 and is pending renewal or deletion.
```

**Comment by boq** [comment]
Thanks for info. I'm trying to contact @mikeemoo, since he holds registration.

For now, use openmods.info.

**Comment by AnrDaemon** [comment]
I'm using it, but it has about zero documentation. On any of the openmods. And ingame help is also all botched, and I barely can make heads to tails.

**Comment by apemanzilla** [comment]
@AnrDaemon I wrote a program to provide browsable documentation for attached OpenPeripheral peripherals, which you can download like so:

`pastebin get 3NPXAasm opdoc`

It requires an advanced computer and it will show tabs with documentation for each attached peripheral.

**Comment by boq** [comment]
Ugh, really, this again?

There are [multiple ways](https://openmods.info/faq.html#op-0) to get documentation, including command to generate offline HTML document.

**Comment by AnrDaemon** [comment]
I'm talking about OpenBlocks documentation. I.e. console commands, like ob_inventory.

**Comment by boq** [comment]
You mean [this](https://openmods.info/faq.html#ob-1) or ![this](https://cloud.githubusercontent.com/assets/754542/16546976/847e66e8-415c-11e6-94ff-e6eaf1267294.png) ?

I don't bother with recipes, since NEI/JEI/TMI/Wikis are enough. About sensor: just place it in creative and play.

**Comment by AnrDaemon** [comment]
> just place it in creative and play.

That's what ducumentation is for - to save time "playing" and, possible, missing an important feature, and do actual work instead.

**Comment by boq** [comment]
It's not software engineering project, it's game that in vanilla version does not tell you how to make pickaxe.

Also, I don't see your point. Every function on sensor is documented. And, frankly speaking, how much are time can anyone "waste" on figuring out what methods `getMobIds` and `getMobData` do?
