### ISSUE TITLE
Receiving an error!

### ISSUE THREAD

**Issue by iNightmaree** [OpenMods/OpenPeripheral#270]
Earlier I had attached two resonant energy cells by wired modem to my computer then proceeded to wrap as a peripheral. On server reboot, I find this in the console: https://puu.sh/qCMuX/cb658975be.png

Mod Versions (all for 1.7.10):

ComputerCraft - 1.75
OpenPeripheralAddons - 0.5.1
OpenPeripheralCore - 1.3
OpenPeripheralIntergration-0.5

**Comment by boq** [comment]
This is mostly harmless and caused by slight bug in other mod's code (client-only interface kept on server). Nothing we can do on our side, unfortunately.
