### ISSUE TITLE
Update to 1.12.2

### ISSUE THREAD

**Issue by Rosentti** [OpenMods/OpenPeripheral#276]
I am sorry to post this here, but computercraft has been updated to 1.12.2 so i would like this to be ported to 1.12.2, along with the other openperipheral mods.

**Comment by dmarcuse** [comment]
[Plethora](http://www.computercraft.info/forums2/index.php?/topic/27321-mc-189-1112-plethora/) covers a lot of the functionality OpenPeripherals implemented.

**Comment by boq** [comment]
@apemanzilla Sorry, but how this information relates to THIS mod?

Anyway, I'm naturally aware that this mod is not ported, so this is something that does not have to be reported.

Of course, I will port this eventually...

**Comment by Rosentti** [comment]
thank you

**Comment by dmarcuse** [comment]
@boq I was suggesting an alternative for the time being, since it supports 1.12 and has much of the same functionality.

**Comment by boq** [comment]
I saw what you did. Anyway, that was irrelevant to this issue. Answer to "I have Windows issue" is not "Use Linux".

**Comment by dmarcuse** [comment]
I'd argue that a more apt comparison is Windows XP (or some other unsupported version) and Linux

**Comment by golyalpha** [comment]
Had this discussion a year ago, still not updated...
